FROM node:16-alpine as development
ENV NODE_ENV development

# Add work directory
WORKDIR /app

# Cache and Install dependencies
COPY package.json .
COPY package-lock.json .

# Run npm install (Install dependencies)
RUN npm i 

# Copy Files

COPY . .

# Expose port 
EXPOSE 3000

# start the app

CMD [ "npm", "run start" ];